---
- name: include_task systemd.yml
  include_tasks: systemd.yml

- name: systemd start rgw container
  systemd:
    name: ceph-radosgw@rgw.{{ ansible_facts['hostname'] }}.{{ item.instance_name }}
    state: started
    enabled: true
    masked: false
    daemon_reload: true
  with_items: "{{ rgw_instances }}"
