---
- name: set _crash_handler_called before restart
  set_fact:
    _crash_handler_called: true

- name: restart the ceph-crash service
  systemd:
    name: ceph-crash@{{ ansible_facts['hostname'] }}
    state: restarted
    enabled: true
    masked: false
    daemon_reload: true
  ignore_errors: true
  when: hostvars[inventory_hostname]['_crash_handler_called'] | default(false) | bool

- name: set _crash_handler_called after restart
  set_fact:
    _crash_handler_called: false
